name: Sync to HuggingFace Hub
on:
  push:
    branches: [main]

  # to run this manually from the Actions tab
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: [self-hosted, linux, legion]
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            lfs: true
      - name: Configure Hugging Face remote
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote | grep -q space && \
            git remote set-url space https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment || \
            git remote add space https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment

      - name: Push to Hub with LFS
        env:
          HF: ${{ secrets.HF }}
        run: |
#          git lfs push --all https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment
          git push --force https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment main
