name: Sync to HuggingFace Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: [self-hosted, linux, legion]
    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs
          git lfs install --skip-repo

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Ensure LFS Migration
        run: |
          git lfs migrate import --include="test.ipynb" --everything --yes

      - name: Configure Hugging Face Remote
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote set-url space https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment || \
          git remote add space https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment

      - name: Push to Hub with LFS
        run: |
          git lfs push --all space main
          git push space main