name: Sync to HuggingFace Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: [self-hosted, linux, legion]
    steps:
      - name: Install Git LFS (Fedora)
        run: |
          if ! command -v git-lfs &> /dev/null; then
            sudo dnf install -y git-lfs  # Fedora uses `dnf` instead of `apt`
            git lfs install --skip-repo
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true  # Ensures LFS files are fetched

      - name: Ensure LFS Migration (Fix history)
        run: |
          git lfs migrate import --include="test.ipynb" --everything --yes

      - name: Configure Hugging Face Remote
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote set-url space "https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment" || \
          git remote add space "https://steinkelsson:$HF@huggingface.co/spaces/steinkelsson/FinalAssignment"

      - name: Push to Hub with LFS
        run: |
          git lfs push --all space main  # Push LFS objects first
          git push space main